name: CD

on:
  push:
    tags:
      - "*"

jobs:
  deploy-docs-to-notion:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm link
      - run: md-to-notion -t ${{ secrets.NOTION_API_TOKEN }} -p ${{ secrets.MD_TO_NOTION_PAGE_ID }} -g vrerv/md-to-notion/blob/main -v .
